services:
  - type: web
    name: instagram-fake-profile-detector
    env: python
    plan: free
    buildCommand: |
      python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip
      pip install --force-reinstall --no-cache-dir Flask numpy pandas scikit-learn requests gunicorn webdriver-manager selenium joblib chromedriver-autoinstaller
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
