services:
  - name: flask-app
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
    buildCommand: |
      apt-get update && apt-get install -y wget unzip curl
      curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb
      dpkg -i chrome.deb || apt-get -fy install
      rm chrome.deb
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
      wget -N https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip -d /usr/local/bin/
      rm chromedriver_linux64.zip
      chmod +x /usr/local/bin/chromedriver
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:10000 app:app
