services:
  - type: web
    name: instagram-fake-profile-detector
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget curl unzip
      wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y /tmp/chrome.deb
      CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
      wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
      unzip /tmp/chromedriver.zip -d /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip
      pip install --force-reinstall --no-cache-dir Flask numpy pandas scikit-learn requests gunicorn selenium joblib
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: GOOGLE_CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROMEDRIVER_PATH
        value: "/usr/local/bin/chromedriver"
