services:
  - type: web
    name: instagram-fake-profile-detector
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget -q -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y /tmp/chrome.deb
      python -m venv venv
      source venv/bin/activate
      python -m pip install --upgrade pip
      pip install --force-reinstall --no-cache-dir Flask numpy pandas scikit-learn requests gunicorn webdriver-manager selenium joblib chromedriver-autoinstaller
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: GOOGLE_CHROME_BIN
        value: "/usr/bin/google-chrome"
